apiVersion: v1
kind: Pod
metadata:
  name: crasher
spec:
  restartPolicy: Always
  containers:
  - name: crasher
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo 'starting'; sleep 2; exit 1"]